"""
Django settings for gami_konnect project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import environ
from pathlib import Path

# Initialize environ
env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read the .env file only if it exists (primarily for local development)
env_file = os.path.join(BASE_DIR, '.env')
if os.path.exists(env_file):
    environ.Env.read_env(env_file)

# Import pusher for real-time notifications
import pusher

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'whitenoise',
    'storages',
    'cloudinary_storage',
    'cloudinary',
    'django_apscheduler',
    
    # Local apps
    'core',
    'games',
    'accounts',
    'shops',
    'admin_panel',
    'activities',
    'competitions',
    'progression',
    'payments',
    'feeds',
    'notifications',
]

APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    
    # Role-based access control for gamer/shop-owner roles
    'accounts.middleware.RoleAccessMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gami_konnect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processor.site_style',
                'core.context_processor.firebase_config',
                'core.context_processor.global_site_context',
                'core.context_processor.admin_competition_context',
                'core.context_processor.admin_notification_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'gami_konnect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Check if Render's PostgreSQL URL is provided in the environment
if 'DATABASE_URL' in os.environ:
    # Use django-environ to parse the Postgres URL automatically
    DATABASES = {
        'default': env.db('DATABASE_URL')
    }
    
    # Use Cloudinary and WhiteNoise ONLY in production
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Fallback to local MySQL configuration for your laptop
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST'),
            'PORT': env('DB_PORT'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }


CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': env('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': env('CLOUDINARY_API_SECRET', default=''),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

# Internationalization
USE_I18N = True

# Localisation
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise settings to ignore missing files during post-processing
WHITENOISE_MANIFEST_STRICT = False


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Project metadata and base URLs
PROJECT_NAME = env('PROJECT_NAME', default='GamiKonnect')

# Dynamically set SITE_URL based on environment
if 'RENDER_EXTERNAL_URL' in os.environ:
    SITE_URL = os.environ.get('RENDER_EXTERNAL_URL')
elif env('SITE_URL', default=''):
    SITE_URL = env('SITE_URL')
else:
    # If no environment variable is set, default to localhost
    SITE_URL = 'http://localhost:8000'

# Ensure SITE_URL doesn't end with a slash for consistency
SITE_URL = SITE_URL.rstrip('/')


# Email configuration
EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    default=('django.core.mail.backends.smtp.EmailBackend'
             if env('EMAIL_HOST', default='')
             else 'django.core.mail.backends.console.EmailBackend')
)

EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='no-reply@gamikonnect.com')
SUPPORT_EMAIL = env('SUPPORT_EMAIL', default='support@gamikonnect.com')
ADMIN_EMAIL = env('ADMIN_EMAIL', default='admin@gamikonnect.com')

# Client-side Firebase config
FIREBASE_CLIENT_CONFIG = {
    'api_key': env('FIREBASE_API_KEY', default=''),
    'auth_domain': env('FIREBASE_AUTH_DOMAIN', default=''),
    'project_id': env('FIREBASE_PROJECT_ID', default=''),
    'storage_bucket': env('FIREBASE_STORAGE_BUCKET', default=''),
    'messaging_sender_id': env('FIREBASE_MESSAGING_SENDER_ID', default=''),
    'app_id': env('FIREBASE_APP_ID', default=''),
    'measurement_id': env('FIREBASE_MEASUREMENT_ID', default=''),
}

# M-PESA DARAJA API CONFIGURATION
MPESA_ENVIRONMENT = os.getenv('MPESA_ENVIRONMENT', 'sandbox')
MPESA_CONSUMER_KEY = os.getenv('MPESA_CONSUMER_KEY')
MPESA_CONSUMER_SECRET = os.getenv('MPESA_CONSUMER_SECRET')
MPESA_SHORTCODE = os.getenv('MPESA_SHORTCODE')
MPESA_PASSKEY = os.getenv('MPESA_PASSKEY')


# Paystack Configuration
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')



# Notifications settings
NOTIFICATION_EMAIL_BATCH_SIZE = 100  # Process emails in batches
NOTIFICATION_RETENTION_DAYS = 30  # General notification retention
NOTIFICATION_CLEANUP_HOUR = 2  # Run cleanup at 2 AM

# Pusher Real-Time Notifications Configuration
# Pusher provides managed WebSocket infrastructure without consuming Render free tier
PUSHER_CLIENT = pusher.Pusher(
    app_id=os.environ.get('PUSHER_APP_ID', 'your_local_app_id'),
    key=os.environ.get('PUSHER_KEY', 'your_local_key'),
    secret=os.environ.get('PUSHER_SECRET', 'your_local_secret'),
    cluster=os.environ.get('PUSHER_CLUSTER', 'your_local_cluster'),
    ssl=True
)