# Generated by Django 6.0.4 on 2026-05-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0005_competitionregistration_paid_at_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mpesatransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "M-Pesa Transaction",
                "verbose_name_plural": "M-Pesa Transactions",
            },
        ),
        migrations.AddField(
            model_name="mpesatransaction",
            name="competition_registration",
            field=models.OneToOneField(
                blank=True,
                help_text="The competition registration this payment is for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="competitions.competitionregistration",
            ),
        ),
        migrations.AddField(
            model_name="mpesatransaction",
            name="is_simulated",
            field=models.BooleanField(
                default=False,
                help_text="If True, this is a simulated payment for testing purposes.",
            ),
        ),
    ]
