# Generated by Django 6.0.4 on 2026-07-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_mpesatransaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesatransaction",
            name="refund_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mpesatransaction",
            name="refund_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mpesatransaction",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mpesatransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                    ("REFUND_PENDING", "Refund Pending"),
                    ("REFUND_FAILED", "Refund Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
