# Generated by Django 6.0.4 on 2026-07-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_mpesatransaction_refund_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesatransaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("COMPETITION", "Competition Registration"),
                    ("AD", "Advertisement"),
                    ("SUBSCRIPTION", "Community Subscription"),
                    ("ARENA_FEE", "Arena/Shop Fee"),
                ],
                default="COMPETITION",
                help_text="Category of this payment for revenue tracking.",
                max_length=20,
            ),
        ),
    ]
