# Generated by Django 5.2.8 on 2025-12-02 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='WHO WE ARE', max_length=100)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='about/')),
                ('is_active', models.BooleanField(default=True)),
                ('active_players', models.CharField(default='Active Players', max_length=50)),
                ('competitions', models.CharField(default='Competitions', max_length=50)),
                ('platforms', models.CharField(default='Platforms', max_length=50)),
                ('active_players_count', models.CharField(default='10K+', max_length=50)),
                ('competitions_count', models.CharField(default='100+', max_length=50)),
                ('platforms_count', models.CharField(default='4', max_length=50)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(default='Feature Name i.e Communities', max_length=50)),
                ('feature_description', models.TextField(default='Feature Description')),
                ('feature_icon', models.CharField(default='fas fa-users', help_text='Font Awesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Feature Card',
                'verbose_name_plural': 'Feature Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_right_text', models.CharField(default='© 2025 GamiKonnect. All rights reserved.', max_length=255)),
                ('ownership_text', models.CharField(default='A product by JM | In partnership with Biztimam Ventures', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Quick Links', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Trending Now', max_length=100)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='games/')),
                ('status', models.CharField(default='Trending', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(default='Sports', max_length=100)),
                ('platform', models.CharField(default='PS4', max_length=100)),
                ('rating', models.FloatField(default=5)),
                ('stats', models.CharField(default='12K+ players', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(default='Home', max_length=100)),
                ('link_icon', models.CharField(blank=True, default='fas fa-home', help_text='Font Awesome icon class', max_length=50)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navigation Link',
                'verbose_name_plural': 'Navigation Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='platforms/')),
                ('description', models.TextField()),
                ('stats', models.CharField(default='12K+ players', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='OUR PLATFORMS', max_length=100)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Platform Heading',
                'verbose_name_plural': 'Platform Headings',
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='GamiKonnect', max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='logo/')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project Detail',
                'verbose_name_plural': 'Project Details',
            },
        ),
        migrations.CreateModel(
            name='SiteStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(choices=[('Arial', 'Arial'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Poppins', 'Poppins'), ('Nunito', 'Nunito'), ('Other', 'Other (specify below)')], default='Roboto', max_length=50)),
                ('custom_font_family', models.CharField(blank=True, help_text="If 'Other', specify font family name.", max_length=100)),
                ('font_color', models.CharField(default='#222222', help_text='Hex color for main text.', max_length=20)),
                ('font_size', models.CharField(default='16px', help_text='CSS font size, e.g. 16px or 1rem.', max_length=10)),
                ('background_color', models.CharField(default='#ffffff', help_text='Hex color for page background.', max_length=20)),
                ('primary_color', models.CharField(default='#007bff', help_text='Primary accent color.', max_length=20)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Secondary accent color.', max_length=20)),
                ('link_color', models.CharField(default='#007bff', help_text='Link color.', max_length=20)),
                ('button_color', models.CharField(default='#28a745', help_text='Button background color.', max_length=20)),
                ('button_text_color', models.CharField(default='#ffffff', help_text='Button text color.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Style',
                'verbose_name_plural': 'Site Styles',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('background_image', models.ImageField(upload_to='sliders/')),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footersection')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['order'],
            },
        ),
    ]
