# Generated by Django 5.2.8 on 2025-12-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
