# Generated by Django 5.2.8 on 2025-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectdetail_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecard',
            name='feature_icon',
            field=models.ImageField(blank=True, upload_to='features/'),
        ),
    ]
