# Generated by Django 5.2.8 on 2025-12-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_featurecard_feature_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='TRENDING NOW', max_length=100)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Game Heading',
                'verbose_name_plural': 'Game Headings',
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='badge_text',
        ),
        migrations.RemoveField(
            model_name='game',
            name='content',
        ),
        migrations.RemoveField(
            model_name='game',
            name='heading',
        ),
    ]
