# Generated by Django 5.2.8 on 2025-12-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gameheading_remove_game_badge_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='LATEST EVENTS', max_length=100)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Event Heading',
                'verbose_name_plural': 'Event Headings',
            },
        ),
    ]
