# Generated by Django 5.2.8 on 2025-12-02 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_eventheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='Used to identify sections in code', unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Content Section',
                'verbose_name_plural': 'Content Sections',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SectionHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(blank=True, max_length=100)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('subheading', models.CharField(blank=True, help_text='Optional smaller text below heading', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.OneToOneField(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='heading', to='core.section')),
            ],
            options={
                'verbose_name': 'Section Heading',
                'verbose_name_plural': 'Section Headings',
                'ordering': ['section__order'],
            },
        ),
        migrations.DeleteModel(
            name='EventHeading',
        ),
        migrations.DeleteModel(
            name='GameHeading',
        ),
        migrations.DeleteModel(
            name='PlatformHeading',
        ),
    ]
