# Generated by Django 5.2.8 on 2025-12-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_section_sectionheading_delete_eventheading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='link_icon',
            field=models.ImageField(blank=True, upload_to='nav_icons/'),
        ),
    ]
