# Generated by Django 5.2.8 on 2026-04-09 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                            ("SECURITY", "Security Event"),
                            ("SYSTEM", "System Event"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A summary of the event (e.g., 'Updated opening hours for GamiKonnect')."
                    ),
                ),
                (
                    "meta_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unstructured data about the event (e.g., old vs new values, IP address).",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed the action. Null if done by the system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities_performed",
                        to="accounts.account",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["target_content_type", "target_object_id"],
                        name="activities__target__be318d_idx",
                    ),
                    models.Index(
                        fields=["actor", "action_type"],
                        name="activities__actor_i_bd4da3_idx",
                    ),
                ],
            },
        ),
    ]
