# Generated by Django 6.0.4 on 2026-04-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="description",
            field=models.TextField(
                help_text="A human-readable summary of the event (e.g., 'Updated opening hours for GameHub')."
            ),
        ),
    ]
