# Generated by Django 6.0.4 on 2026-04-28 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("activities", "0003_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="badges/achievements/"
                    ),
                ),
                (
                    "condition_key",
                    models.CharField(
                        help_text="Internal key used by signals to trigger this (e.g., 'first_win', 'five_checkins')",
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Amateur, Bronze, Gold",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "required_points",
                    models.PositiveIntegerField(
                        help_text="XP/Points required to reach this level"
                    ),
                ),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="badges/levels/"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Numeric order of the level (e.g., 1 for Amateur, 2 for Beginner). Used for progression logic.",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Level",
                "verbose_name_plural": "Levels",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="description",
            field=models.TextField(help_text="A human-readable summary of the event."),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="meta_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Unstructured data about the event."
            ),
        ),
        migrations.CreateModel(
            name="GamerAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.achievement",
                    ),
                ),
                (
                    "gamer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocked_achievements",
                        to="accounts.gamer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gamer Achievement",
                "verbose_name_plural": "Gamer Achievements",
                "unique_together": {("gamer", "achievement")},
            },
        ),
    ]
