# Generated by Django 6.0.4 on 2026-05-01 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_gamer_current_level"),
        ("activities", "0005_update_activity_types_and_activitylog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="activity",
            new_name="activities__gamer_i_55c970_idx",
            old_name="activities__gamer_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="activity",
            new_name="activities__activit_f3d1c5_idx",
            old_name="activities__type_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="activities__gamer_i_7cf8c2_idx",
            old_name="activitylog_gamer_timestamp_idx",
        ),
        migrations.AddField(
            model_name="achievement",
            name="xp",
            field=models.PositiveIntegerField(
                default=0, help_text="XP awarded for unlocking this achievement"
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="gamer",
            field=models.ForeignKey(
                blank=True,
                help_text="The gamer associated with this activity log (if applicable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to="accounts.gamer",
            ),
        ),
    ]
