# Generated by Django 6.0.4 on 2026-05-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activities",
            "0006_rename_activities__gamer_timestamp_idx_activities__gamer_i_55c970_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="target_object_id",
            field=models.CharField(
                blank=True,
                help_text="Can store integer or UUID values",
                max_length=255,
                null=True,
            ),
        ),
    ]
