# Generated by Django 5.2.8 on 2025-12-17 11:12

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='Firebase UID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='Firebase UID')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(choices=[('gamer', 'Gamer'), ('shop_owner', 'Shop Owner')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pending Registration',
                'verbose_name_plural': 'Pending Registrations',
            },
        ),
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.account')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Shop Owner',
                'verbose_name_plural': 'Shop Owners',
            },
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.account')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('custom_username', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Custom Username')),
                ('bio', models.TextField(default='Bio')),
                ('about', models.TextField(blank=True, default='About')),
                ('date_of_birth', models.DateField(default=datetime.date(2025, 1, 1))),
                ('location', models.CharField(default='', max_length=255)),
                ('platforms', models.JSONField(default=list)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(default=0, help_text="User's total points earned from gaming activities")),
                ('games', models.ManyToManyField(blank=True, related_name='gamers', to='games.game')),
            ],
            options={
                'verbose_name': 'Gamer',
                'verbose_name_plural': 'Gamers',
            },
            bases=('accounts.account',),
        ),
    ]
