# Generated by Django 6.0.4 on 2026-04-28 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("activities", "0004_achievement_level_alter_activitylog_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamer",
            name="current_level",
            field=models.ForeignKey(
                blank=True,
                help_text="The gamer's current progression level.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="activities.level",
            ),
        ),
    ]
