# Generated by Django 6.0.4 on 2026-05-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_gender_pendingregistration_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamer",
            name="is_pwa",
            field=models.BooleanField(
                default=False,
                help_text="If True, indicates the gamer has PWA (Persons With Albinism) or other specified status.",
                verbose_name="Is PWA",
            ),
        ),
    ]
