# Generated by Django 6.0.4 on 2026-05-19 07:01

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
import feeds.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_gamer_is_pwa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Text content of the post",
                        max_length=5000,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The gamer who created this post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="accounts.gamer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gamer",
                    models.ForeignKey(
                        help_text="The gamer who liked this post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_posts",
                        to="accounts.gamer",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="The post being liked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="feeds.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Like",
                "verbose_name_plural": "Likes",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Comment text", max_length=1000),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The gamer who made this comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="accounts.gamer",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="The post being commented on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="feeds.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        help_text="Whether this is an image or video",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Image or video file stored on Cloudinary",
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to="feeds/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "mp4",
                                    "webm",
                                    "mov",
                                    "avi",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        help_text="Use this for image uploads (auto-validates 3MB limit)",
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to="feeds/",
                        validators=[feeds.models.validate_image_size],
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Use this for video uploads (auto-validates 10MB limit)",
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to="feeds/",
                        validators=[feeds.models.validate_video_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Order of media in the post (for display)"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="The post this media belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="feeds.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Media",
                "verbose_name_plural": "Post Media",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_at"], name="feeds_post_created_2bd9a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at"], name="feeds_post_author__711664_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["post", "gamer"], name="feeds_like_post_id_9cbbfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["gamer", "-created_at"], name="feeds_like_gamer_i_906e28_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("post", "gamer")},
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "created_at"], name="feeds_comme_post_id_d0cc2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author", "created_at"], name="feeds_comme_author__a4fdb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postmedia",
            index=models.Index(
                fields=["post", "order"], name="feeds_postm_post_id_b65698_idx"
            ),
        ),
    ]
