# Generated by Django 6.0.4 on 2026-05-19 07:12

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Image or video file stored on Cloudinary",
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="feeds/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "mp4",
                            "webm",
                            "mov",
                            "avi",
                        ]
                    )
                ],
            ),
        ),
    ]
