# Generated by Django 5.2.8 on 2025-12-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Shop Name')),
                ('location', models.CharField(max_length=255)),
                ('screen_number', models.PositiveIntegerField(default=0)),
                ('base_price_per_hour', models.DecimalField(decimal_places=2, default=0, help_text='Default price for games without specific pricing', max_digits=6)),
                ('opening_hours', models.TextField(blank=True, default='Opening Hours')),
                ('closing_hours', models.TextField(blank=True, default='Closing Hours')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('games_available', models.ManyToManyField(blank=True, related_name='shops', to='games.game')),
                ('owners', models.ManyToManyField(related_name='shops', to='accounts.shopowner')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='GamePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_premium', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_prices', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Game Pricing',
                'verbose_name_plural': 'Game Pricing',
                'unique_together': {('shop', 'game')},
            },
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, help_text='e.g., Special editions, models, etc.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('console_type', models.ForeignKey(limit_choices_to={'category__name': 'Console'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop_consoles', to='games.platform')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consoles', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Console',
                'verbose_name_plural': 'Consoles',
                'unique_together': {('shop', 'console_type')},
            },
        ),
    ]
