# Generated by Django 6.0.1 on 2026-02-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_submitted_by_email_shop_submitted_by_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='building',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_permit',
            field=models.FileField(blank=True, help_text='Upload your business permit for verification', null=True, upload_to='business_permits/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city_town',
            field=models.CharField(blank=True, max_length=100, verbose_name='City/Town'),
        ),
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of your shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='floor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='room_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='base_price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default price for games without specific pricing', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(help_text='Full address or landmarks', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='screen_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Stations/Screens'),
        ),
    ]
