# Generated by Django 6.0.2 on 2026-03-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_shop_building_shop_business_permit_shop_city_town_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="city_town",
        ),
        migrations.AddField(
            model_name="shop",
            name="address",
            field=models.CharField(
                default="", help_text="Full address or landmarks", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="city",
            field=models.CharField(default="", max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="building",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="shop",
            name="business_permit",
            field=models.FileField(
                default="business_permits/placeholder.pdf",
                help_text="Upload your business permit for verification",
                upload_to="business_permits/",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="closing_hours",
            field=models.TextField(default="Closing Hours"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="description",
            field=models.TextField(
                default="", help_text="A brief description of your shop"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="floor",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="shop",
            name="location",
            field=models.CharField(default="", max_length=100, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="logo",
            field=models.ImageField(
                default="shop_logos/placeholder.png", upload_to="shop_logos/"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Shop Name"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="opening_hours",
            field=models.TextField(default="Opening Hours"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="room_number",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="shop",
            name="screen_number",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of screens"
            ),
        ),
    ]
