# Generated by Django 6.0.4 on 2026-04-22 11:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Shown to the gamer when they earn this achievement."
                    ),
                ),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="progression/achievement_badges/",
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("first_registration", "First Competition Registered"),
                            ("first_completion", "First Competition Completed"),
                            ("first_win", "First Win (Top 3 Finish)"),
                            ("competition_count", "Compete N Times"),
                            ("xp_milestone", "Reach XP Milestone"),
                            ("level_reached", "Reach a Level"),
                            ("participation_hours", "Participate for N Hours"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "threshold",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="The value that triggers this achievement. For first_registration/first_completion/first_win: always 1. For competition_count: number of competitions. For xp_milestone: XP amount. For level_reached: level order number. For participation_hours: total hours.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive achievements will not be awarded to gamers.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["achievement_type", "threshold"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Amateur, Bronze, Champion",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "min_xp",
                    models.PositiveIntegerField(
                        help_text="Minimum cumulative XP required to reach this level.",
                        unique=True,
                    ),
                ),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True,
                        help_text="Badge image displayed on the gamer's profile and dashboard.",
                        null=True,
                        upload_to="progression/level_badges/",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#35A8F0",
                        help_text="Hex colour used to style this level's badge in the UI (e.g. #FFD700).",
                        max_length=7,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Sort order — lower number = lower level. Used to determine rank progression.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Level",
                "verbose_name_plural": "Levels",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="GamerLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reached_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the gamer reached this level.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gamer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gamer_level",
                        to="accounts.gamer",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gamers_at_level",
                        to="progression.level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gamer Level",
                "verbose_name_plural": "Gamer Levels",
            },
        ),
        migrations.CreateModel(
            name="GamerAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earned_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_by",
                        to="progression.achievement",
                    ),
                ),
                (
                    "gamer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="accounts.gamer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gamer Achievement",
                "verbose_name_plural": "Gamer Achievements",
                "ordering": ["-earned_at"],
                "unique_together": {("gamer", "achievement")},
            },
        ),
    ]
