# Generated by Django 6.0.4 on 2026-05-23 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_pendingregistration_is_pwa"),
        ("progression", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={
                "ordering": ["category", "target_value"],
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
            },
        ),
        migrations.AddField(
            model_name="achievement",
            name="category",
            field=models.CharField(
                choices=[
                    ("ONBOARDING", "Onboarding & Setup"),
                    ("COMMUNITY", "Community & Networking"),
                    ("CONTENT", "Content Creation"),
                    ("SOCIAL", "Social Interaction"),
                    ("COMPETITION", "Competitions"),
                    ("LEAGUE", "Community Leagues"),
                    ("PROGRESSION", "Level & XP Progression"),
                    ("LOYALTY", "Loyalty & Streaks"),
                    ("HIDDEN", "Hidden / Secret"),
                    ("SEASONAL", "Seasonal Events"),
                ],
                default="ONBOARDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="is_hidden",
            field=models.BooleanField(
                default=False, help_text="Hide from users until unlocked?"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="metric_key",
            field=models.CharField(
                blank=True,
                help_text="The exact field name in GamerStats (e.g. 'competitions_won')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="target_value",
            field=models.PositiveIntegerField(
                default=1, help_text="The number required to unlock this achievement"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="xp_reward",
            field=models.PositiveIntegerField(
                default=50, help_text="XP awarded to the gamer when unlocked"
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="achievement_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_registration", "First Competition Registered"),
                    ("first_completion", "First Competition Completed"),
                    ("first_win", "First Win (Top 3 Finish)"),
                    ("competition_count", "Compete N Times"),
                    ("xp_milestone", "Reach XP Milestone"),
                    ("level_reached", "Reach a Level"),
                    ("participation_hours", "Participate for N Hours"),
                ],
                db_index=True,
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="threshold",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="GamerStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("communities_joined", models.PositiveIntegerField(default=0)),
                ("gamers_invited", models.PositiveIntegerField(default=0)),
                ("comments_made", models.PositiveIntegerField(default=0)),
                ("posts_made", models.PositiveIntegerField(default=0)),
                ("posts_with_10_likes", models.PositiveIntegerField(default=0)),
                ("posts_with_25_likes", models.PositiveIntegerField(default=0)),
                ("posts_with_75_likes", models.PositiveIntegerField(default=0)),
                ("competitions_joined", models.PositiveIntegerField(default=0)),
                ("competitions_won", models.PositiveIntegerField(default=0)),
                ("leagues_joined", models.PositiveIntegerField(default=0)),
                ("leagues_won", models.PositiveIntegerField(default=0)),
                ("login_streak_days", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gamer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progression_stats",
                        to="accounts.gamer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gamer Stat",
                "verbose_name_plural": "Gamer Stats",
            },
        ),
    ]
