# Generated by Django 6.0.4 on 2026-04-16 20:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("games", "0002_game_is_verified"),
        ("shops", "0004_remove_shop_city_town_shop_address_shop_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "integer_id",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, unique=True
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("scheduled_time", models.DateTimeField()),
                (
                    "entry_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("max_participants", models.PositiveIntegerField()),
                ("rules", models.TextField(blank=True)),
                ("timeline", models.TextField(blank=True)),
                ("points_1st", models.PositiveIntegerField(blank=True, null=True)),
                ("points_2nd", models.PositiveIntegerField(blank=True, null=True)),
                ("points_3rd", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "points_4_to_10",
                    models.PositiveIntegerField(
                        blank=True, help_text="Points for positions 4 to 10", null=True
                    ),
                ),
                (
                    "points_beyond_10",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Points for positions 11 and beyond (0 if not set)",
                        null=True,
                    ),
                ),
                (
                    "registration_open_delay",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Minutes after approval before registration opens",
                    ),
                ),
                ("registration_opens_at", models.DateTimeField(blank=True, null=True)),
                (
                    "registration_closes_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Auto-set to 1 day before scheduled_time",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Admin Review"),
                            ("rejected", "Rejected"),
                            ("approved", "Live"),
                            ("registration_open", "Registration Open"),
                            ("registration_closed", "Registration Closed"),
                            ("ongoing", "Ongoing"),
                            ("checkin_submitted", "Check-in Submitted"),
                            ("results_pending", "Results Pending"),
                            ("results_submitted", "Results Submitted"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_competitions",
                        to="accounts.account",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competitions",
                        to="games.game",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competitions",
                        to="games.platform",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competitions",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition",
                "verbose_name_plural": "Competitions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unique_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("checked_in", models.BooleanField(default=False)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("code_expired", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="competitions.competition",
                    ),
                ),
                (
                    "gamer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competition_registrations",
                        to="accounts.gamer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition Registration",
                "verbose_name_plural": "Competition Registrations",
                "unique_together": {("competition", "gamer")},
            },
        ),
        migrations.CreateModel(
            name="CompetitionResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, help_text="Null if gamer was a no-show", null=True
                    ),
                ),
                ("points_awarded", models.PositiveIntegerField(default=0)),
                ("is_no_show", models.BooleanField(default=False)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="competitions.competition",
                    ),
                ),
                (
                    "gamer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competition_results",
                        to="accounts.gamer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition Result",
                "verbose_name_plural": "Competition Results",
                "ordering": ["rank"],
                "unique_together": {("competition", "gamer")},
            },
        ),
    ]
