# Generated by Django 6.0.4 on 2026-04-18 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="registration_open_delay",
        ),
        migrations.AddField(
            model_name="competition",
            name="age_restricted",
            field=models.BooleanField(
                default=True,
                help_text="If True, only gamers aged 18 and above may register. ID verification required on competition day.",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="competition_end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time the competition ends. Used to compute participation hours.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="prize_gift_description",
            field=models.TextField(
                blank=True,
                help_text="Description of the gift prize and how it is distributed across the top 3.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="prize_money_1st_pct",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Percentage of total prize money awarded to 1st place (e.g. 50 for 50%).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="prize_money_2nd_pct",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Percentage of total prize money awarded to 2nd place.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="prize_money_3rd_pct",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Percentage of total prize money awarded to 3rd place.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="prize_money_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total money prize pool for this competition.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="prize_type",
            field=models.CharField(
                blank=True,
                choices=[("points", "Points"), ("money", "Money"), ("gift", "Gift")],
                help_text="Type of prize for this competition. Set by admin during approval.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="competitionresult",
            name="auto_allocated",
            field=models.BooleanField(
                default=False,
                help_text="True if points were automatically allocated upon results submission (points prize type only).",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="created_by",
            field=models.ForeignKey(
                help_text="The admin or shop owner who created this competition.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_competitions",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="entry_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Entry fee for the competition. Admin can adjust during review.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="max_participants",
            field=models.PositiveIntegerField(
                help_text="Maximum number of gamers allowed to register."
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="points_1st",
            field=models.PositiveIntegerField(
                blank=True, help_text="XP/points awarded to 1st place.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="points_2nd",
            field=models.PositiveIntegerField(
                blank=True, help_text="XP/points awarded to 2nd place.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="points_3rd",
            field=models.PositiveIntegerField(
                blank=True, help_text="XP/points awarded to 3rd place.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="points_4_to_10",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="XP/points awarded to positions 4 through 10.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="points_beyond_10",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="XP/points awarded to positions 11 and beyond. Defaults to 0 if not set.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="registration_closes_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time registration closes. Set by admin during approval.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="registration_opens_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time registration opens. Set by admin during approval.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason provided by admin when rejecting a competition submission.",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="rules",
            field=models.TextField(
                blank=True,
                help_text="Competition rules. Age restriction and ID requirement will be appended automatically.",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="scheduled_time",
            field=models.DateTimeField(
                help_text="The date and time the competition starts."
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Admin Review"),
                    ("rejected", "Rejected"),
                    ("approved", "Live"),
                    ("registration_open", "Registration Open"),
                    ("registration_closed", "Registration Closed"),
                    ("ongoing", "Ongoing"),
                    ("checkin_submitted", "Check-in Submitted"),
                    ("results_pending", "Results Pending"),
                    ("results_submitted", "Results Submitted"),
                    ("pending_prize_verification", "Pending Prize Verification"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="competitionregistration",
            name="checked_in_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the shop owner verified this gamer's code. Used for participation hours calculation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="competitionregistration",
            name="code_expired",
            field=models.BooleanField(
                default=False,
                help_text="Set to True once the gamer has been verified and the code is no longer valid.",
            ),
        ),
        migrations.AlterField(
            model_name="competitionregistration",
            name="is_cancelled",
            field=models.BooleanField(
                default=False,
                help_text="Marks a registration as cancelled. Slot remains occupied.",
            ),
        ),
        migrations.AlterField(
            model_name="competitionregistration",
            name="unique_code",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique code generated at registration. Used by shop owner to verify gamer on competition day.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="competitionresult",
            name="is_no_show",
            field=models.BooleanField(
                default=False,
                help_text="True if the gamer registered but did not show up. No points are awarded.",
            ),
        ),
        migrations.AlterField(
            model_name="competitionresult",
            name="points_awarded",
            field=models.PositiveIntegerField(
                default=0,
                help_text="XP/points awarded to the gamer based on their rank and the competition's prize structure.",
            ),
        ),
        migrations.AlterField(
            model_name="competitionresult",
            name="rank",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Final rank of the gamer. Null if the gamer was a no-show.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="competitionresult",
            name="verified",
            field=models.BooleanField(
                default=False, help_text="True once the admin has verified the results."
            ),
        ),
    ]
