# Generated by Django 6.0.4 on 2026-05-01 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_gamer_current_level"),
        ("competitions", "0002_remove_competition_registration_open_delay_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approved"),
                            ("reject", "Rejected"),
                            ("open_registration", "Open Registration"),
                            ("close_registration", "Close Registration"),
                            ("start", "Competition Started"),
                            ("end", "Competition Ended"),
                            ("confirm_checkins", "Checkins Confirmed"),
                            ("verify_results", "Results Verified"),
                            ("submit_results", "Results Submitted"),
                            ("submit_checkins", "Checkins Submitted"),
                            ("auto_transition", "Automated Transition"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField(blank=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="competitions.competition",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition Audit Log",
                "verbose_name_plural": "Competition Audit Logs",
                "ordering": ["-performed_at"],
            },
        ),
    ]
