# Generated by Django 6.0.4 on 2026-05-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0003_competitionauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionauditlog",
            name="performed_by_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
