# Generated by Django 6.0.4 on 2026-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0004_competitionauditlog_performed_by_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionregistration",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when payment was completed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="competitionregistration",
            name="payment_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number used to pay for this registration.",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="competitionregistration",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Payment status for this registration.",
                max_length=20,
            ),
        ),
    ]
