# Generated by Django 6.0.4 on 2026-05-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0005_competitionregistration_paid_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="gender_rules",
            field=models.CharField(
                choices=[
                    ("all", "All (All Genders)"),
                    ("male", "Male (Male Gamers Only)"),
                    ("female", "Female (Female Gamers Only)"),
                ],
                default="all",
                help_text="Gender restriction for the competition.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="is_pwa_only",
            field=models.BooleanField(
                default=False,
                help_text="If True, the competition is only for PWA.",
                verbose_name="PWA Only",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="team_size",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of players per team (currently default is 1 for individual).",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="max_participants",
            field=models.PositiveIntegerField(
                help_text="Maximum number of participants allowed to register."
            ),
        ),
        migrations.AlterField(
            model_name="competitionregistration",
            name="unique_code",
            field=models.CharField(
                editable=False,
                help_text="Unique 6-character code generated at registration.",
                max_length=6,
                unique=True,
            ),
        ),
    ]
