# Generated by Django 6.0.4 on 2026-05-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "competitions",
            "0006_competition_gender_rules_competition_is_pwa_only_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("live", "Live"),
                    ("registration_open", "Registration Open"),
                    ("registration_closed", "Registration Closed"),
                    ("ongoing", "Ongoing"),
                    ("checkin_submitted", "Check-in Submitted"),
                    ("results_pending", "Results Pending"),
                    ("results_submitted", "Results Submitted"),
                    ("pending_prize_verification", "Pending Prize Verification"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="draft",
                max_length=30,
            ),
        ),
    ]
