# Generated by Django 6.0.4 on 2026-07-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0007_alter_competition_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("registration_open", "Registration Open"),
                    ("registration_closed", "Registration Closed"),
                    ("ongoing", "Ongoing"),
                    ("checkin_submitted", "Check-in Submitted"),
                    ("results_pending", "Results Pending"),
                    ("results_submitted", "Results Submitted"),
                    ("pending_prize_verification", "Pending Prize Verification"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="draft",
                max_length=30,
            ),
        ),
    ]
