# Generated by Django 6.0.4 on 2026-07-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0009_normalize_competition_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="guidelines",
            field=models.TextField(
                blank=True,
                help_text="Specific guidelines for the competition (especially for virtual ones).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="is_virtual",
            field=models.BooleanField(
                default=False, help_text="If True, the competition is virtual/online."
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="platform_or_shop_link",
            field=models.CharField(
                blank=True,
                help_text="Platform name (e.g. Discord, Twitch) for virtual competitions, or shop link.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="is_pwa_only",
            field=models.BooleanField(
                default=False,
                help_text="If True, the competition is only for PWD.",
                verbose_name="PWD Only",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="points_1st",
            field=models.PositiveIntegerField(
                default=150, help_text="Points awarded to 1st place."
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="points_2nd",
            field=models.PositiveIntegerField(
                default=100, help_text="Points awarded to 2nd place."
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="points_3rd",
            field=models.PositiveIntegerField(
                default=70, help_text="Points awarded to 3rd place."
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="points_4_to_10",
            field=models.PositiveIntegerField(
                default=30, help_text="Points awarded to positions 4 through 10."
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="points_beyond_10",
            field=models.PositiveIntegerField(
                default=10, help_text="Points awarded to positions 11 and beyond."
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="prize_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("points", "Points Only"),
                    ("money_points", "Money + Points"),
                    ("gift_points", "Gift + Points"),
                ],
                help_text="Type of prize for this competition. Set by admin during approval.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("registration", "Registration"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="competitionregistration",
            name="unique_code",
            field=models.CharField(
                editable=False,
                help_text="Unique 5-character code generated at registration.",
                max_length=5,
                unique=True,
            ),
        ),
    ]
