# Generated by Django 6.0.4 on 2026-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0010_competition_guidelines_competition_is_virtual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionregistration",
            name="unique_code",
            field=models.CharField(
                editable=False,
                help_text="Unique 5-character code generated at registration.",
                max_length=10,
                unique=True,
            ),
        ),
    ]
