# Generated by Django 6.0.4 on 2026-07-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0011_alter_competitionregistration_unique_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="admin_reviewed",
            field=models.BooleanField(
                default=False,
                help_text="True once an admin has reviewed a deployed competition.",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="suspension_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason provided by admin when suspending a live competition.",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("registration", "Registration"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("suspended", "Suspended"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="competitionauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Approved"),
                    ("reject", "Rejected"),
                    ("suspend", "Suspended"),
                    ("edit_prizes", "Prize Details Edited"),
                    ("edit_results", "Results Edited"),
                    ("open_registration", "Open Registration"),
                    ("close_registration", "Close Registration"),
                    ("start", "Competition Started"),
                    ("end", "Competition Ended"),
                    ("confirm_checkins", "Checkins Confirmed"),
                    ("verify_results", "Results Verified"),
                    ("submit_results", "Results Submitted"),
                    ("submit_checkins", "Checkins Submitted"),
                    ("auto_transition", "Automated Transition"),
                    ("other", "Other"),
                ],
                max_length=40,
            ),
        ),
    ]
