# Generated by Django 6.0.1 on 2026-01-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
