# Generated by Django 6.0.4 on 2026-05-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_gamer_is_pwa"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "criteria_type",
                    models.CharField(
                        choices=[
                            ("level", "By Level"),
                            ("game", "By Game"),
                            ("competition", "By Competition"),
                            ("custom", "Custom User List"),
                            ("payment_status", "By Payment Status"),
                            ("all_users", "All Users"),
                        ],
                        db_index=True,
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "criteria_data",
                    models.JSONField(
                        default=dict,
                        help_text="JSON data defining the group. Format depends on criteria_type. Examples: {'levels': [1,2,3]}, {'games': ['chess', 'scrabble']}, {'user_ids': [1,2,3]}, {'competition_id': 5}, {'payment_status': 'completed'}",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member_count",
                    models.IntegerField(
                        default=0, help_text="Cached count of users matching this group"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("system", "System"),
                            ("competition", "Competition"),
                            ("payment", "Payment"),
                            ("achievement", "Achievement"),
                            ("level_up", "Level Up"),
                            ("account", "Account"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "message_template",
                    models.TextField(
                        blank=True,
                        help_text="Template with merge fields like {{username}}, {{level}}, {{game}}",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System notifications are created programmatically",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this notification expires and can be auto-deleted",
                        null=True,
                    ),
                ),
                (
                    "total_recipients",
                    models.IntegerField(
                        default=0,
                        help_text="Denormalized count of NotificationRecipient records",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "-created_at"],
                        name="notificatio_categor_6dc2ff_idx",
                    ),
                    models.Index(
                        fields=["importance", "expires_at"],
                        name="notificatio_importa_37c8b7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="notifications.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.gamer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_a5e20e_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_b99848_idx",
                    ),
                    models.Index(
                        fields=["user", "delivery_status"],
                        name="notificatio_user_id_ae7629_idx",
                    ),
                ],
                "unique_together": {("notification", "user")},
            },
        ),
        migrations.CreateModel(
            name="NotificationSchedule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        db_index=True, help_text="When this notification should be sent"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="notificatio_status_80583c_idx",
                    )
                ],
            },
        ),
    ]
