# Generated by Django 6.0.4 on 2026-05-18 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_gamer_is_pwa"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notificationrecipient",
            name="notificatio_user_id_a5e20e_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationrecipient",
            name="notificatio_user_id_b99848_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationrecipient",
            name="notificatio_user_id_ae7629_idx",
        ),
        migrations.AlterUniqueTogether(
            name="notificationrecipient",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="notificationrecipient",
            name="admin_user",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_notifications",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="notificationrecipient",
            name="gamer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="accounts.gamer",
            ),
        ),
        migrations.AddField(
            model_name="notificationrecipient",
            name="shop_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="accounts.shopowner",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["gamer", "is_read"], name="notificatio_gamer_i_072ecc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["gamer", "-created_at"], name="notificatio_gamer_i_ee7e4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["gamer", "delivery_status"],
                name="notificatio_gamer_i_7b279e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["shop_owner", "is_read"], name="notificatio_shop_ow_84379a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["shop_owner", "-created_at"],
                name="notificatio_shop_ow_93d41a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["admin_user", "is_read"], name="notificatio_admin_u_777715_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["admin_user", "-created_at"],
                name="notificatio_admin_u_85757f_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="notificationrecipient",
            name="user",
        ),
    ]
